# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_drawio_render_extension
project_short_description: Jupyterlab extension to just render the drawio diagram
    (viewer in Jupyterlab)
python_name: jupyterlab_drawio_render_extension
repository: ''
test: true

